mp3c/urls.py
from django.urls import include, path
from django.views.generic import RedirectView

from mp3c import views

app_name = 'mp3c'

app_name = 'mp3c'
urlpatterns = [
    path('', RedirectView.as_view(pattern_name='mp3c:asteroid-list')),
    path('asteroids/', views.asteroid_list, name='asteroid-list'),
    path('asteroids/<int:pk>/', views.asteroid_detail, name='asteroid-detail'),
]

ocapyweb/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mp3c.urls')),
]

mp3c/models.py
from django.db import models
from django.urls import reverse


class Asteroid(models.Model):
    name = models.CharField(
        unique=True,
        max_length=64,
    )

    def get_absolute_url(self):
        return reverse('mp3c:asteroid-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class Mass(models.Model):
    asteroid = models.ForeignKey(Asteroid, models.CASCADE)
    value = models.FloatField()
    uncertainty = models.FloatField(null=True, blank=True)
    reference = models.CharField(max_length=64)

    def __str__(self):
        return '%0.3g' % self.value

mp3c/views.py
from django.shortcuts import get_object_or_404, render

from mp3c.models import Asteroid


def asteroid_list(request):
    context = {'asteroids': Asteroid.objects.all()}
    response = render(request, 'asteroid_list.html', context)
    return response


def asteroid_detail(request, pk):
    asteroid = get_object_or_404(Asteroid, pk=pk)
    context = {'asteroid': asteroid}
    response = render(request, 'asteroid_detail.html', context)
    return response

mp3c/templates/asteroid_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{{ asteroid.name }}</title>
</head>
<body>
<h1>{{ asteroid.name }}</h1>
<p>ID: {{ asteroid.id }}</p>


<h2>Masses</h2>

{% if asteroid.mass_set.all %}
<ul>
{% for mass in asteroid.mass_set.all %}
    <li>{{ mass.value|stringformat:"0.4e" }} {% if mass.uncertainty %}<small>+/- {{ mass.uncertainty|stringformat:"0.4e" }}</small>{% endif %} [{{ mass.reference }}]</li>
{% endfor %}
</ul>
{% else %}
<p>There are no mass measurements for this asteroid.</p>
{% endif %}

</body>
</html>

mp3c/templates/asteroid_list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Asteroids list</title>
</head>
<body>
<p>[<a href="{% url 'admin:index' %}">Admin site</a>]</p>
<h1>Asteroids list</h1>
{% if asteroids %}
<ul>
{% for asteroid in asteroids %}
  <li><a href="{{ asteroid.get_absolute_url }}">{{ asteroid.name }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>There are no asteroids!</p>
{% endif %}
</body>
</html>